[build]
  command = "npm run build"
  functions = "lambda"
  publish = "dist"

[context.deploy-preview]
  publish = "dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
  query = {id = ":id"}

  [[redirects]]
  from = "/"
  to = "/index.html"
  status = 200 

  [[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/theme"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200

  [dev]
  command = "npm run build"
  port = 8888
  targetPort = 3000
  publish = "dist"
  jwtRolePath = "app_metadata.authorization.roles"
  jwtSecret = "MY_JWT_SECRET_VALUE"
  autoLaunch = true
  framework = "#custom"
  [dev.https]
    certFile = "cert.pem"
    keyFile = "key.pem"
 
 command = "sed -i \"s|HEADER_PLACEHOLDER|${PROD_API_LOCATION}|g\" netlify.toml && npm run build"   